In [1]:
#importing libraries
import pandas as pd 
from sklearn import * 
from sklearn import metrics 
import numpy as np

In [2]:
#reading data from .csv file
data=pd.read_csv('weath.csv') 
df = pd.DataFrame(data)

In [3]:
#top 5 raws of dataset
data.head()

,Date,Temperature (K),Relative Humidity (%),Rainfall (kg/m2),Wheat,Rice,Cotton
0,2004-rabi,300.88,75.71,0.140014,0,0,1
1,2004-kharif,300.80,76.23,0.144404,1,1,1
2,2005-rabi,300.71,76.76,0.148794,1,0,0
3,2005-kharif,300.63,77.29,0.153184,1,0,0
4,2006-rabi,300.56,77.78,0.156907,1,0,1

In [4]:
#bottom 5 rows of dataset
data.tail()

,Date,Temperature (K),Relative Humidity (%),Rainfall (kg/m2),Wheat,Rice,Cotton
17,2012-kharif,301.38,72.88,0.102849,1,0,0
18,2013-Rabi,301.21,73.79,0.116836,1,1,0
19,2013-kharif,301.12,74.26,0.122831,1,0,0
20,2014-Rabi,301.04,74.73,0.128826,0,1,1
21,2014-kharif,300.96,75.21,0.134821,1,0,1

In [5]:
#setting target variable for test-train split
x0=df.drop('Rice',axis=1) 
x0=x0.drop('Wheat',axis=1) 
x0=x0.drop('Cotton',axis=1)
x0=x0.drop('Date',axis=1) 

y0=df.Rice 
y1=df.Wheat
y2=df.Cotton

In [6]:
#test-train split for all the crops
from sklearn.model_selection import train_test_split
X_train0, X_test0, y_train0, y_test0 = train_test_split(x0,y0, test_size=0.1) 
X_train1, X_test1, y_train1, y_test1 = train_test_split(x0,y1, test_size=0.1)
X_train2, X_test2, y_train2, y_test2 = train_test_split(x0,y2, test_size=0.1)

In [7]:
#temperature vs date line plot
from bokeh.plotting import figure,output_file,show
output_file("file.html")
x=list(data['Date'])
y=list(data['Temperature (K)'])
def remv(string):
    newstr = string[:4]
    return newstr

for i in range(len(x)):
    name=remv(x[i])
    x[i]=name
from bokeh.plotting import figure, output_notebook, show
#output_notebook()
p = figure(x_axis_label='Year',y_axis_type='log',y_axis_label='Temperature')
p.line(x,y, line_width=1,color='green')
show(p)

In [8]:
#Relative humidity vs date line plot
x=list(data['Date'])
y=list(data['Relative Humidity (%)'])
def remv(string):
    newstr = string[:4]
    return newstr

for i in range(len(x)):
    name=remv(x[i])
    x[i]=name
from bokeh.plotting import figure, output_notebook, show
#output_notebook()
p = figure(x_axis_label='Year',y_axis_label='Relative Humidity (%)')
p.line(x,y, line_width=1,color='red')
show(p)

In [9]:
#Rainfall vs date line plot
x=list(data['Date'])
y=list(data['Rainfall (kg/m2)'])
def remv(string):
    newstr = string[:4]
    return newstr

for i in range(len(x)):
    name=remv(x[i])
    x[i]=name
from bokeh.plotting import figure, output_notebook, show
#output_notebook()
p = figure(x_axis_label='Year',y_axis_label='Rainfall (kg/m2)')
p.line(x,y, line_width=1,color='blue')

show(p)

In [10]:

from sklearn.naive_bayes import GaussianNB 
#create a Gaussian Classifier
gnb = GaussianNB()
gnb1 = GaussianNB() 
gnb2 = GaussianNB()

#train the model using the training sets
gnb.fit(X_train0,y_train0) 
gnb1.fit(X_train1,y_train1)
gnb2.fit(X_train2,y_train2)

#user input for temperature, humidity, and rainfall
temp=float(input("Enter the temperature in kelvin: "))
humidity=float(input("Enter the humidity in %: "))
rain=float(input("Enter the rainfall in kg/m2/day: "))

Crop=int(input("Enter the necessary crop : 1 for Rice, 2 for Wheat, 3 for Cotton: "))
if Crop==1 : 
    pred=gnb.predict([[temp,humidity,rain]]) 
    prob=gnb.predict_proba([[temp,humidity,rain]]) 
    print("Predicted values of given samples is : ",pred) 
    print("The probability of predicting that Rice cannot be grown for the input is : ",prob[:,0]) 
    print("The probability of predicting Rice can be grown for the input is : ",prob[:,1])

elif Crop==2 : 
    pred=gnb1.predict([[temp,humidity,rain]]) 
    prob=gnb1.predict_proba([[temp,humidity,rain]]) 
    print("Predicted values of given samples is : ",pred) 
    print("The probability of predicting that Wheat cannot be grown for the input is : ",prob[:,0]) 
    print("The probability of predicting Wheat can be grown for the input is : ",prob[:,1])

elif Crop==3 : 
    pred=gnb2.predict([[temp,humidity,rain]]) 
    prob=gnb2.predict_proba([[temp,humidity,rain]]) 
    print("Predicted values of given samples is : ",pred) 
    print("The probability of predicting that Cotton cannot be grown for the input is : ",prob[:,0]) 
    print("The probability of predicting Cotton can be grown for the input is : ",prob[:,1])

else: 
    print("Invalid input") 
    exit(0)

Predicted values of given samples is :  [0]
The probability of predicting that Cotton cannot be grown for the input is :  [0.65533248]
The probability of predicting Cotton can be grown for the input is :  [0.34466752]

C:\Users\sidri\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
C:\Users\sidri\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(